//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTRider.uEpisodes.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Show}\\Season {season}\\S{season:00}E{episode:00}. {title}")]
        public string CopyToPattern {
            get {
                return ((string)(this["CopyToPattern"]));
            }
            set {
                this["CopyToPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Show} - S{season:00}E{episode:00}. {title}")]
        public string MoveToPattern {
            get {
                return ((string)(this["MoveToPattern"]));
            }
            set {
                this["MoveToPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSettings {
            get {
                return ((bool)(this["ShowSettings"]));
            }
            set {
                this["ShowSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLog {
            get {
                return ((bool)(this["ShowLog"]));
            }
            set {
                this["ShowLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalExtensions {
            get {
                return ((string)(this["AdditionalExtensions"]));
            }
            set {
                this["AdditionalExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShowMappings {
            get {
                return ((string)(this["ShowMappings"]));
            }
            set {
                this["ShowMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSystemMonitorFolder {
            get {
                return ((string)(this["FileSystemMonitorFolder"]));
            }
            set {
                this["FileSystemMonitorFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemAutoCopy {
            get {
                return ((bool)(this["FileSystemAutoCopy"]));
            }
            set {
                this["FileSystemAutoCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemAutoMove {
            get {
                return ((bool)(this["FileSystemAutoMove"]));
            }
            set {
                this["FileSystemAutoMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemRunMonitor {
            get {
                return ((bool)(this["FileSystemRunMonitor"]));
            }
            set {
                this["FileSystemRunMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string uTorrentAddress {
            get {
                return ((string)(this["uTorrentAddress"]));
            }
            set {
                this["uTorrentAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string uTorrentCredentials {
            get {
                return ((string)(this["uTorrentCredentials"]));
            }
            set {
                this["uTorrentCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool uTorrentAutoCopy {
            get {
                return ((bool)(this["uTorrentAutoCopy"]));
            }
            set {
                this["uTorrentAutoCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool uTorrentAutoMove {
            get {
                return ((bool)(this["uTorrentAutoMove"]));
            }
            set {
                this["uTorrentAutoMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool uTorrentAutoStopSeeding {
            get {
                return ((bool)(this["uTorrentAutoStopSeeding"]));
            }
            set {
                this["uTorrentAutoStopSeeding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool uTorrentRunMonitor {
            get {
                return ((bool)(this["uTorrentRunMonitor"]));
            }
            set {
                this["uTorrentRunMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sample\r\nExtras\r\nDocumentary\r\n")]
        public string IgnoreDirectories {
            get {
                return ((string)(this["IgnoreDirectories"]));
            }
            set {
                this["IgnoreDirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"^(?'show'.*)Series\s*(?'season'\d+)\s*Episode\s*(?'episode'\d+)
^(?'show'.*)Season\s*(?'season'\d+)\s*Episode\s*(?'episode'\d+)
^(?'show'.*)S\s*(?'season'\d+)\s*E\s*(?'episode'\d+)
^S\s*(?'season'\d+)\s*E\s*(?'episode'\d+)
^(?'show'.*)(?'season'\d+)x(?'episode'\d+)
^(?'show'.*)(?'season'\d\d)x(?'episode'\d\d)
^(?'show'[^\d]*)(?'season'\d)(?'episode'\d+)
^(?'show'[^\d]*)(?'season'\d\d)(?'episode'\d+)
^(?'show'.*)(?'season'\d)(?'episode'\d\d)")]
        public string FileNamePatterns {
            get {
                return ((string)(this["FileNamePatterns"]));
            }
            set {
                this["FileNamePatterns"] = value;
            }
        }
    }
}
